import Foundation

private enum BuildInfoGeneratorError: Error, CustomStringConvertible, Sendable {
  case invalidArguments
  case unreadableVersionFile(path: String, reason: String)
  case invalidVersion(String)

  var description: String {
    switch self {
    case .invalidArguments:
      return "usage: SoonGenerateBuildInfo <version-file> <output-file>"
    case .unreadableVersionFile(let path, let reason):
      return "failed to read Soon build version from \(path): \(reason)"
    case .invalidVersion(let version):
      return "invalid Soon build version: \(version)"
    }
  }
}

private enum SoonGenerateBuildInfo {
  private static let defaultVersion = "dev"

  static func run() throws {
    let arguments = Array(CommandLine.arguments.dropFirst())
    guard arguments.count == 2 else {
      throw BuildInfoGeneratorError.invalidArguments
    }

    let versionFile = arguments[0]
    let outputFile = arguments[1]
    let version = try readVersion(from: versionFile)

    guard isValidVersion(version) else {
      throw BuildInfoGeneratorError.invalidVersion(version)
    }

    let source = """
      // Generated by SoonGenerateBuildInfo. Do not edit.
      public enum BuildInfo {
        public static let appVersion = "\(version)"
      }

      """
    let outputURL = URL(fileURLWithPath: outputFile)

    try FileManager.default.createDirectory(
      at: outputURL.deletingLastPathComponent(),
      withIntermediateDirectories: true
    )
    try source.write(to: outputURL, atomically: true, encoding: .utf8)
  }

  private static func readVersion(from path: String) throws -> String {
    guard FileManager.default.fileExists(atPath: path) else {
      return defaultVersion
    }

    do {
      return try String(contentsOfFile: path, encoding: .utf8)
        .trimmingCharacters(in: .whitespacesAndNewlines)
    } catch {
      throw BuildInfoGeneratorError.unreadableVersionFile(
        path: path,
        reason: String(describing: error)
      )
    }
  }

  private static func isValidVersion(_ version: String) -> Bool {
    guard !version.isEmpty else { return false }

    return version.unicodeScalars.allSatisfy { scalar in
      switch scalar.value {
      case 43, 45, 46, 48...57, 65...90, 95, 97...122:
        return true
      default:
        return false
      }
    }
  }
}

do {
  try SoonGenerateBuildInfo.run()
} catch {
  let message = "error: \(error)\n"
  FileHandle.standardError.write(Data(message.utf8))
  exit(EXIT_FAILURE)
}
